services:
  search-service-1:
    build: ./search-service
    ports:
      - 8080:8080
    environment:
      - 'SERVER_PORT=8080'
    depends_on:
      - cache
  
  # scale-out
  # search-service-2:
  #   build: ./search-service
  #   ports:
  #     - 8081:8081
  #   environment:
  #     - "SERVER_PORT=8081"

  cache:
    image: redis:alpine # slim 버전
    ports:
      - 6379:6379
