services:
  search-service-1:
    container_name: search-service-1
    build: ./search-service
    ports:
      - 8080:8080
    environment:
      - 'server.port=8080'
      - 'spring.application.name=search-service-1'
      - 'spring.redis.host=cache'
      - 'eureka.client.service-url.defaultZone=http://discovery-service:8761/eureka'
    depends_on:
      - cache
      - discovery-service

  # scale-out
  search-service-2:
    container_name: search-service-2
    build: ./search-service
    ports:
      - 8081:8081
    environment:
      - 'server.port=8081'
      - 'spring.application.name=search-service-2'
      - 'spring.redis.host=cache'
      - 'eureka.client.service-url.defaultZone=http://discovery-service:8761/eureka'
    depends_on:
      - cache
      - discovery-service

  cache:
    container_name: cache
    image: redis:alpine # slim 버전
    ports:
      - 6379:6379

  api-gateway:
    container_name: api-gateway
    build: ./api-gateway
    ports:
      - 8000:8000
    environment:
      - 'server.port=8000'
      - 'eureka.client.service-url.defaultZone=http://discovery-service:8761/eureka'
    depends_on:
      - discovery-service

  discovery-service:
    container_name: discovery-service
    build: ./discovery-service
    ports:
      - 8761:8761
    environment:
      - 'server.port=8761'
