drop table keyword if exists;

create table keyword (
  id bigint generated by default as identity,
  query varchar(255),
  search_count bigint,
  primary key (id)
);

-- alter table keyword drop constraint if exists UK3dwp2i22d2jq65undaw580hx;
-- alter table keyword add constraint UK3dwp2i22d2jq65undaw580hx unique (query);